apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 80            # Port to access the service
      targetPort: 3000    # Container port your app listens on
      nodePort: 31000     # Optional: Choose a static NodePort (must be between 30000–32767)
